"""gmail processed messages (M14)

Adds the ``gmail_processed_messages`` table: deduplication state for the read-only
Gmail connector, keyed by Gmail message id. Additive only; no existing table is
modified. Stores no message content and no OAuth secret.

Revision ID: 2e323b64d4cd
Revises: f163ed341c79
Create Date: 2026-08-15 15:50:31.780082
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e323b64d4cd"
down_revision: str | None = "f163ed341c79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gmail_processed_messages",
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("scan_id", sa.String(length=64), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_gmail_processed_messages")),
    )
    with op.batch_alter_table("gmail_processed_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gmail_processed_messages_processed_at"), ["processed_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gmail_processed_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gmail_processed_messages_processed_at"))

    op.drop_table("gmail_processed_messages")
    # ### end Alembic commands ###
