"""email scans and threat artifact type

Revision ID: 36db7b14f265
Revises: 400e888de0f7
Create Date: 2026-07-22 07:44:18.832595
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36db7b14f265"
down_revision: str | None = "400e888de0f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=1024), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("evidence_strength", sa.Float(), nullable=False),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("url_count", sa.Integer(), nullable=False),
        sa.Column("malicious_url_count", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_scans")),
    )
    with op.batch_alter_table("email_scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_scans_sender"), ["sender"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_scans_verdict"), ["verdict"], unique=False)

    with op.batch_alter_table("threat_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("artifact_type", sa.String(length=16), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_threat_entries_artifact_type"), ["artifact_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threat_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_entries_artifact_type"))
        batch_op.drop_column("artifact_type")

    with op.batch_alter_table("email_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_scans_verdict"))
        batch_op.drop_index(batch_op.f("ix_email_scans_sender"))

    op.drop_table("email_scans")
    # ### end Alembic commands ###
