"""url scan intelligence fields

Revision ID: 400e888de0f7
Revises: 5787a237aafc
Create Date: 2026-07-21 15:45:07.555312
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "400e888de0f7"
down_revision: str | None = "5787a237aafc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_scans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category", sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column("evidence_strength", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("sources", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_scans", schema=None) as batch_op:
        batch_op.drop_column("sources")
        batch_op.drop_column("evidence_strength")
        batch_op.drop_column("category")

    # ### end Alembic commands ###
