"""add threat_entries table

Revision ID: 5787a237aafc
Revises: bea95b07769d
Create Date: 2026-07-21 09:10:02.566519
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5787a237aafc"
down_revision: str | None = "bea95b07769d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threat_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact", sa.String(length=2048), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("indicators", sa.JSON(), nullable=False),
        sa.Column("first_detected", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detection_count", sa.Integer(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("block_source", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threat_entries")),
    )
    with op.batch_alter_table("threat_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_threat_entries_artifact_hash"), ["artifact_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_threat_entries_last_detected"), ["last_detected"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_threat_entries_verdict"), ["verdict"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threat_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_entries_verdict"))
        batch_op.drop_index(batch_op.f("ix_threat_entries_last_detected"))
        batch_op.drop_index(batch_op.f("ix_threat_entries_artifact_hash"))

    op.drop_table("threat_entries")
    # ### end Alembic commands ###
