"""file_scans and file_investigations

Revision ID: 98f21bd4afba
Revises: 0a1e3ad455de
Create Date: 2026-07-26 06:19:30.698096
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98f21bd4afba"
down_revision: str | None = "0a1e3ad455de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_investigations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scan_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_investigations")),
    )
    with op.batch_alter_table("file_investigations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_investigations_scan_id"), ["scan_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_file_investigations_status"), ["status"], unique=False)

    op.create_table(
        "file_scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("fingerprints", sa.JSON(), nullable=False),
        sa.Column("file_kind", sa.String(length=32), nullable=False),
        sa.Column("detected_mime", sa.String(length=128), nullable=False),
        sa.Column("entropy", sa.Float(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("evidence_strength", sa.Float(), nullable=False),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("indicator_count", sa.Integer(), nullable=False),
        sa.Column("url_count", sa.Integer(), nullable=False),
        sa.Column("malicious_url_count", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_scans")),
    )
    with op.batch_alter_table("file_scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_scans_file_kind"), ["file_kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_scans_filename"), ["filename"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_scans_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_scans_verdict"), ["verdict"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_scans_verdict"))
        batch_op.drop_index(batch_op.f("ix_file_scans_sha256"))
        batch_op.drop_index(batch_op.f("ix_file_scans_filename"))
        batch_op.drop_index(batch_op.f("ix_file_scans_file_kind"))

    op.drop_table("file_scans")
    with op.batch_alter_table("file_investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_investigations_status"))
        batch_op.drop_index(batch_op.f("ix_file_investigations_scan_id"))

    op.drop_table("file_investigations")
    # ### end Alembic commands ###
