"""add url_scans table

Revision ID: bea95b07769d
Revises: 04edb1fcee88
Create Date: 2026-07-20 17:07:25.258328
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bea95b07769d"
down_revision: str | None = "04edb1fcee88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_url_scans")),
    )
    with op.batch_alter_table("url_scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_url_scans_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_url_scans_verdict"), ["verdict"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_scans_verdict"))
        batch_op.drop_index(batch_op.f("ix_url_scans_created_at"))

    op.drop_table("url_scans")
    # ### end Alembic commands ###
