"""email investigations

Revision ID: fee449f5845f
Revises: 36db7b14f265
Create Date: 2026-07-23 09:47:41.965558
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fee449f5845f"
down_revision: str | None = "36db7b14f265"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_investigations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scan_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_investigations")),
    )
    with op.batch_alter_table("email_investigations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_investigations_scan_id"), ["scan_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_email_investigations_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_investigations_status"))
        batch_op.drop_index(batch_op.f("ix_email_investigations_scan_id"))

    op.drop_table("email_investigations")
    # ### end Alembic commands ###
