"""UI backend gateway.

The presentation layer's HTTP client for the embedded FastAPI backend, plus a
health poller and an async runner. This is the only channel from the UI to
application services (ADR-002): the UI never imports services or infrastructure
directly.
"""

from core.domain.graph_view import (
    ConnectedEntity,
    GraphAnalyticsSummary,
    GraphEdgeView,
    GraphNodeView,
    GraphPathView,
    GraphSearchResult,
    GraphSelection,
    GraphSnapshotView,
    GraphView,
)
from ui.backend.async_runner import AsyncRunner
from ui.backend.client import (
    ArtifactDTO,
    AttachmentDTO,
    AuthMechanismDTO,
    AuthResult,
    AuthUser,
    BackendClient,
    BodyDTO,
    CampaignDTO,
    CampaignSummaryDTO,
    Contribution,
    EmailScanResult,
    EmbeddedUrlDTO,
    FileIndicatorsDTO,
    FileOverviewDTO,
    FileScanResult,
    GmailEvidenceDTO,
    GmailMessageDetailDTO,
    GmailMessageDTO,
    GmailPreviewDTO,
    GmailSourceDTO,
    GmailStatusDTO,
    GmailSyncDTO,
    GmailUrlDTO,
    HealthComponentDTO,
    HealthResult,
    IncidentDTO,
    IncidentEventDTO,
    IncidentSummaryDTO,
    InvestigationDTO,
    MetricDTO,
    OverviewDTO,
    ScanResult,
    SenderIntelDTO,
    SocOverviewDTO,
    SourceScoreDTO,
    ThreatEntryDTO,
    ThreatStatsDTO,
    ThreatStatus,
    TimelineEventDTO,
)
from ui.backend.health_poller import BackendHealthPoller

__all__ = [
    "ArtifactDTO",
    "AsyncRunner",
    "AttachmentDTO",
    "AuthMechanismDTO",
    "AuthResult",
    "AuthUser",
    "BackendClient",
    "BackendHealthPoller",
    "BodyDTO",
    "CampaignDTO",
    "CampaignSummaryDTO",
    "ConnectedEntity",
    "Contribution",
    "EmailScanResult",
    "EmbeddedUrlDTO",
    "FileIndicatorsDTO",
    "FileOverviewDTO",
    "FileScanResult",
    "GmailEvidenceDTO",
    "GmailMessageDTO",
    "GmailMessageDetailDTO",
    "GmailPreviewDTO",
    "GmailSourceDTO",
    "GmailStatusDTO",
    "GmailSyncDTO",
    "GmailUrlDTO",
    "GraphAnalyticsSummary",
    "GraphEdgeView",
    "GraphNodeView",
    "GraphPathView",
    "GraphSearchResult",
    "GraphSelection",
    "GraphSnapshotView",
    "GraphView",
    "HealthComponentDTO",
    "HealthResult",
    "IncidentDTO",
    "IncidentEventDTO",
    "IncidentSummaryDTO",
    "InvestigationDTO",
    "MetricDTO",
    "OverviewDTO",
    "ScanResult",
    "SenderIntelDTO",
    "SocOverviewDTO",
    "SourceScoreDTO",
    "ThreatEntryDTO",
    "ThreatStatsDTO",
    "ThreatStatus",
    "TimelineEventDTO",
]
