"""Core domain value objects and pure functions."""

from __future__ import annotations

from core.domain.analysis import FeatureContribution, UrlAnalysis, Verdict
from core.domain.copilot import (
    Citation,
    ContextItem,
    ConversationTurn,
    CopilotContext,
    CopilotQuery,
    CopilotResponse,
    CopilotStreamEvent,
    DetectedIntent,
    GroundingViolation,
    IntentKind,
    PromptMetadata,
)
from core.domain.copilot_session import CopilotSession, FocusState
from core.domain.correlation import (
    ArtifactKind,
    ArtifactRef,
    CorrelationLink,
)
from core.domain.events import (
    EventType,
    IntelligenceEvent,
)
from core.domain.file import (
    ArchiveEntry,
    EntropyProfile,
    FileKind,
    FileMetadata,
    FileType,
    Fingerprint,
    FingerprintSet,
    PEImport,
    PEInfo,
    PESection,
    compute_fingerprints,
    describe_metadata,
    identify_type,
    shannon_entropy,
    validate_filename,
)
from core.domain.fusion import (
    FusionResult,
    IntelligenceRelationship,
    ProviderInfo,
    ProviderSummary,
    Severity,
    severity_from_score,
)
from core.domain.graph import (
    GraphEdge,
    GraphNode,
    GraphPath,
    GraphSnapshot,
    NodeType,
    RelationshipType,
)
from core.domain.intelligence import (
    Evidence,
    EvidenceSource,
    IntelligenceReport,
    SourceScore,
    ThreatCategory,
    combine_evidence,
)
from core.domain.investigation import (
    EventKind,
    EvidenceNode,
    InvestigationEvent,
    InvestigationSummary,
    MetadataField,
)
from core.domain.ioc import (
    IocCollection,
    IOCExtractionResult,
    IOCStatistics,
    TaggedIndicator,
    extract_iocs,
    extract_iocs_full,
    ioc_statistics,
    refang,
)
from core.domain.url import Url
from core.domain.value_objects import EntityId

__all__ = [
    "ArchiveEntry",
    "ArtifactKind",
    "ArtifactRef",
    "Citation",
    "ContextItem",
    "ConversationTurn",
    "CopilotContext",
    "CopilotQuery",
    "CopilotResponse",
    "CopilotSession",
    "CopilotStreamEvent",
    "CorrelationLink",
    "DetectedIntent",
    "EntityId",
    "EntropyProfile",
    "EventKind",
    "EventType",
    "Evidence",
    "EvidenceNode",
    "EvidenceSource",
    "FeatureContribution",
    "FileKind",
    "FileMetadata",
    "FileType",
    "Fingerprint",
    "FingerprintSet",
    "FocusState",
    "FusionResult",
    "GraphEdge",
    "GraphNode",
    "GraphPath",
    "GraphSnapshot",
    "GroundingViolation",
    "IOCExtractionResult",
    "IOCStatistics",
    "IntelligenceEvent",
    "IntelligenceRelationship",
    "IntelligenceReport",
    "IntentKind",
    "InvestigationEvent",
    "InvestigationSummary",
    "IocCollection",
    "MetadataField",
    "NodeType",
    "PEImport",
    "PEInfo",
    "PESection",
    "PromptMetadata",
    "ProviderInfo",
    "ProviderSummary",
    "RelationshipType",
    "Severity",
    "SourceScore",
    "TaggedIndicator",
    "ThreatCategory",
    "Url",
    "UrlAnalysis",
    "Verdict",
    "combine_evidence",
    "compute_fingerprints",
    "describe_metadata",
    "extract_iocs",
    "extract_iocs_full",
    "identify_type",
    "ioc_statistics",
    "refang",
    "severity_from_score",
    "shannon_entropy",
    "validate_filename",
]
